url: https://www.sgaiertruss.com

title: Sgaier Truss

keywords: Sgaier Truss

description: Sgaier Truss

address: C3,No.6,Changdun Road,GuanYong Village,Shiqi Town,Panyu District,Guangzhou City,Guangdong Province,China

tel: 020-34562371

email: sales@sgaiertruss.com

facebook: https://www.facebook.com/sgaiertruss

linkedin: https://www.linkedin.com/company/sgaier-truss-co-ltd/

vimeo: https://vimeo.com/stagetruss

exclude:
  - README.md

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/js
    - _assets/css
  compress:
    css: true
    js: true
  gzip: []
