url: https://www.sgaiertruss.com

title: Sgaier Truss

keywords: sgaier truss

description: Sgaier Truss

address: C3,No.6,Changdun Road,GuanYong Village,Shiqi Town,Panyu District,Guangzhou City,Guangdong Province,China

tel: +86-18127852766

email: sales@sgaiertruss.com

facebook: https://www.facebook.com/sgaiertruss

twitter: https://twitter.com/Alutruss

linkedin: https://www.linkedin.com/company/sgaier-truss-co-ltd/

youtube: 

vimeo: https://vimeo.com/stagetruss

exclude:
  - README.md
  - style.css
  - style.js
